"""Formularium constants — the source of truth for every catalog constant.

Edit entries here directly (values, uncertainties, tiers, notes). The Get* nodes
and GetCatalog marshal these specs verbatim; `formularium regen-node` regenerates
the node files wholesale if entries are added or removed.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ConstantSpec:
    symbol: str
    name: str
    value: float             # in `unit`
    unit: str
    mass_dim: float          # natural units (hbar = c = 1); dimensionless iff 0
    tier: str                # established | derived | conjecture
    source: str              # CODATA | PDG | NuFIT | Planck | derived | definition | convention
    uncertainty: float | None = None
    aliases: list[str] = field(default_factory=list)
    notes: str = ''
    related_formulas: list[str] = field(default_factory=list)


CONSTANTS: dict[str, ConstantSpec] = {
    'A_wolf': ConstantSpec(
        symbol='A_wolf',
        name='Wolfenstein A parameter',
        value=0.826,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=0.012,
        notes='CKM hierarchy parameter; A ~ V_cb / V_us^2',
    ),
    'Delta_A_bit': ConstantSpec(
        symbol='Delta_A_bit',
        name='horizon area quantum (dyadic)',
        value=7.2428e-70,
        unit='m^2',
        mass_dim=-2,
        tier='conjecture',
        source='derived',
        uncertainty=1.6e-74,
        notes='Delta_A = 4 l_P^2 ln 2 - the Bekenstein-Mukhanov uniformly-spaced area spectrum (alpha = 4 ln 2 ~ 2.77) reached via the dyadic-thread postulate (geometry-as-bandwidth clause v, separable: its death removes only itself). k-ary threads give 4 ln k; continuum capacity gives no spectrum. Class-level discrimination (alpha ~ 2.8-5.5 vs 8 pi ~ 25.1 vs no imprint) is robust to linewidth limits; adjudication plausibly ET/LISA in the 2030s. Detection at alpha != 4 ln 2 kills it.',
    ),
    'Delta_m21_sq': ConstantSpec(
        symbol='Delta_m21_sq',
        name='solar mass-squared splitting',
        value=7.41e-05,
        unit='eV^2',
        mass_dim=2,
        tier='established',
        source='NuFIT',
        uncertainty=2.1e-06,
    ),
    'Delta_m31_sq': ConstantSpec(
        symbol='Delta_m31_sq',
        name='atmospheric mass-squared splitting',
        value=0.002507,
        unit='eV^2',
        mass_dim=2,
        tier='established',
        source='NuFIT',
        uncertainty=2.7e-05,
        notes='normal ordering',
    ),
    'Delta_m32_sq': ConstantSpec(
        symbol='Delta_m32_sq',
        name='Delta m^2_32 neutrino splitting',
        value=0.0024329,
        unit='eV^2',
        mass_dim=2,
        tier='derived',
        source='derived',
        uncertainty=2.7e-05,
        notes='Delta_m31_sq - Delta_m21_sq (exact identity); ~ Delta_m31_sq since Delta_m21_sq is tiny.',
        related_formulas=['nu_splitting_identity'],
    ),
    'E_S': ConstantSpec(
        symbol='E_S',
        name='Schwinger critical field',
        value=1.32328e+18,
        unit='V/m',
        mass_dim=2,
        tier='established',
        source='derived',
        uncertainty=800000000.0,
        aliases=['Schwinger limit', 'QED critical field'],
        notes="E_S = m_e^2 c^3 / (e hbar) -- the electric field at which the QED vacuum breaks down via e+e- pair creation (Sauter 1931, Schwinger 1951). The scale where 'empty space' stops being linear. DIA-08-1004-004 (Davis 2010) quotes 2x this value (pair rest energy over Compton wavelength convention). Strongest lab fields (petawatt lasers) reach ~1e14-1e15 V/m, four orders below.",
    ),
    'F_faraday': ConstantSpec(
        symbol='F_faraday',
        name='Faraday constant',
        value=96485.33212331001,
        unit='C/mol',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='F = N_A e',
    ),
    'G_F': ConstantSpec(
        symbol='G_F',
        name='Fermi constant',
        value=1.1663787e-05,
        unit='GeV^-2',
        mass_dim=-2,
        tier='established',
        source='CODATA',
        uncertainty=6e-12,
        notes='weak interaction strength',
    ),
    'G_N': ConstantSpec(
        symbol='G_N',
        name='Newtonian gravitational constant',
        value=6.6743e-11,
        unit='m^3/(kg*s^2)',
        mass_dim=-2,
        tier='established',
        source='CODATA',
        uncertainty=1.5e-15,
        notes='G_N = 1/M_Pl^2',
    ),
    'H_0': ConstantSpec(
        symbol='H_0',
        name='Hubble constant',
        value=67.4,
        unit='km/s/Mpc',
        mass_dim=1,
        tier='established',
        source='Planck',
        uncertainty=0.5,
        notes='expansion rate; in tension with the local (SH0ES ~73) measurement',
    ),
    'Lambda_QCD': ConstantSpec(
        symbol='Lambda_QCD',
        name='QCD scale (1-loop nf=3 estimate)',
        value=0.2445,
        unit='GeV',
        mass_dim=1,
        tier='derived',
        source='derived',
        uncertainty=0.05,
        notes='Dimensional-transmutation scale where the running strong coupling diverges. Value = M_Z*exp(-2*pi/(beta0_QCD*alpha_s)) at 1-loop nf=3 (self-consistent with qcd_transmutation); PDG threshold-matched Lambda^(3)_MSbar ~ 0.33 GeV, the ~30% gap is higher-order. Derived from alpha_s alone -- see investigations/orphan-bridges.',
        related_formulas=['qcd_transmutation', 'nucleon_qcd_scale'],
    ),
    'Lambda_cc': ConstantSpec(
        symbol='Lambda_cc',
        name='cosmological constant',
        value=1.0904e-52,
        unit='m^-2',
        mass_dim=2,
        tier='established',
        source='derived',
        uncertainty=2e-54,
        aliases=['Lambda'],
        notes='Lambda = 3 Omega_Lambda H_0^2 / c^2, computed from catalog H_0 (Planck 67.4) and Omega_Lambda (Planck 2018). Symbol is Lambda_cc because sympy reserves "Lambda". In natural units a mass_dim-2 scale; the genuine mystery is the dimensionless ratio Lambda*l_P^2 ~ 2.8e-122 (equivalently N_dS).',
    ),
    'M_Pl': ConstantSpec(
        symbol='M_Pl',
        name='Planck mass',
        value=1.22089e+19,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='derived',
        notes='M_Pl = G_N^(-1/2) (natural units)',
    ),
    'M_W': ConstantSpec(
        symbol='M_W',
        name='W boson mass',
        value=80.377,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.012,
    ),
    'M_Z': ConstantSpec(
        symbol='M_Z',
        name='Z boson mass',
        value=91.1876,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.0021,
    ),
    'N_A': ConstantSpec(
        symbol='N_A',
        name='Avogadro constant',
        value=6.02214076e+23,
        unit='mol^-1',
        mass_dim=0,
        tier='established',
        source='definition',
        notes='defines the mole (SI-exact since 2019)',
    ),
    'N_dS': ConstantSpec(
        symbol='N_dS',
        name='de Sitter horizon capacity',
        value=3.309e+122,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=6e+120,
        notes='Gibbons-Hawking entropy of the de Sitter horizon in nats: 3 pi/(Lambda l_P^2) = A_dS/(4 l_P^2). ESTABLISHED as horizon entropy (and as Bousso\'s N-bound on observable entropy). The identification with total Hilbert-space capacity log dim(H) - kinematic UV = thermodynamic IR - is Banks\' contested CONJECTURE, adopted by geometry-as-bandwidth section 2. "Why is Lambda small?" becomes "why is N large?"; no independent determination of N is on offer.',
    ),
    'Omega_Lambda': ConstantSpec(
        symbol='Omega_Lambda',
        name='dark-energy density parameter',
        value=0.6847,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='Planck',
        uncertainty=0.0073,
        notes='Planck 2018 TT,TE,EE+lowE+lensing. Fraction of critical density in the cosmological constant / dark energy; a genuine dimensionless cosmological input.',
    ),
    'R_gas': ConstantSpec(
        symbol='R_gas',
        name='molar gas constant',
        value=8.31446261815324,
        unit='J/(mol*K)',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='R = N_A k_B',
    ),
    'R_inf': ConstantSpec(
        symbol='R_inf',
        name='Rydberg constant',
        value=10973731.568157,
        unit='m^-1',
        mass_dim=1,
        tier='established',
        source='CODATA',
        uncertainty=1.2e-05,
    ),
    'Ry': ConstantSpec(
        symbol='Ry',
        name='Rydberg energy',
        value=13.60569312299,
        unit='eV',
        mass_dim=1,
        tier='established',
        source='CODATA',
        uncertainty=1.5e-11,
        notes='hydrogen binding scale (13.6 eV)',
    ),
    'S_CHSH_cl': ConstantSpec(
        symbol='S_CHSH_cl',
        name='CHSH classical bound',
        value=2.0,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        notes="Local-hidden-variable maximum of the CHSH correlator (Clauser-Horne- Shimony-Holt 1969, from Bell 1964). Two-line derivation: with deterministic outcomes a, a', b, b' = +-1, the combination a(b+b') + a'(b-b') is always +-2 (one parenthesis is +-2, the other 0); averaging over any hidden-variable distribution preserves the bound. Exact.",
    ),
    'S_IC_triv': ConstantSpec(
        symbol='S_IC_triv',
        name='communication-trivialization threshold',
        value=3.265986323710904,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='4 sqrt(2/3) (Brassard et al. 2006). Above it, noisy super-quantum boxes can be distilled by majority-vote repetition (like a concatenated code) until communication complexity trivializes: one transmitted bit, amortized, unlocks unboundedly many effective remote bits. Lemma 0 of geometry-as-bandwidth (the provable fragment of the no-counterfeiting theorem) targets the regime above this threshold; the interval (2 sqrt(2), 4 sqrt(2/3)] is open, shared with the field.',
    ),
    'S_NS_max': ConstantSpec(
        symbol='S_NS_max',
        name='no-signaling CHSH maximum (PR box)',
        value=4.0,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='Algebraic maximum of the CHSH correlator, attained by the Popescu-Rohrlich box (1994): no-signaling alone permits S = 4. The gap between 2 sqrt(2) and 4 is the explanandum of information causality -- and, on the geometry-as-bandwidth conjecture, of the finiteness of spacetime capacity.',
    ),
    'S_Tsirelson': ConstantSpec(
        symbol='S_Tsirelson',
        name='Tsirelson bound',
        value=2.8284271247461903,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='2 sqrt(2) - the maximal quantum CHSH correlation (classical bound 2, no-signaling maximum 4). Exact; follows from information causality (Pawlowski et al., Nature 461, 1101 (2009)). Geometry-as-bandwidth clause (iv) CONJECTURES this and the covariant entropy bound are one fact - correlations cannot counterfeit channel capacity - pending the region-capacity dictionary (Debt 2). Trivialization threshold 4 sqrt(2/3) ~ 3.266 (Brassard et al.) bounds the provable fragment.',
    ),
    'V_cb': ConstantSpec(
        symbol='V_cb',
        name='CKM |V_cb|',
        value=0.041,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='PDG',
        uncertainty=0.0014,
    ),
    'V_ub': ConstantSpec(
        symbol='V_ub',
        name='CKM |V_ub|',
        value=0.00382,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='PDG',
        uncertainty=0.0002,
    ),
    'V_us': ConstantSpec(
        symbol='V_us',
        name='CKM |V_us|',
        value=0.2243,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='PDG',
        uncertainty=0.0008,
        notes='Cabibbo angle sin',
    ),
    'Z_0': ConstantSpec(
        symbol='Z_0',
        name='impedance of free space',
        value=376.730313412,
        unit='ohm',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=5.9e-08,
        notes='Z_0 = mu_0 c',
    ),
    'a_0': ConstantSpec(
        symbol='a_0',
        name='Bohr radius',
        value=5.29177210544e-11,
        unit='m',
        mass_dim=-1,
        tier='established',
        source='CODATA',
        uncertainty=8.2e-21,
        notes='atomic length scale',
    ),
    'a_e': ConstantSpec(
        symbol='a_e',
        name='electron anomalous magnetic moment',
        value=0.00115965218059,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=1.3e-12,
        notes='a_e = (g-2)/2 ~ alpha/2pi (Schwinger); QED-predicted from alpha',
    ),
    'alpha': ConstantSpec(
        symbol='alpha',
        name='fine-structure constant',
        value=0.0072973525643,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='CODATA',
        uncertainty=1.1e-12,
        aliases=['alpha_em'],
        notes='electromagnetic coupling; = 1/137.035999',
    ),
    'alpha_s': ConstantSpec(
        symbol='alpha_s',
        name='strong coupling at M_Z',
        value=0.1179,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='PDG',
        uncertainty=0.001,
        notes='alpha_s(M_Z), MS-bar',
    ),
    'b_wien': ConstantSpec(
        symbol='b_wien',
        name='Wien displacement-law constant',
        value=0.002897771955,
        unit='m*K',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='blackbody peak wavelength: b = h c / (x k_B), x ~ 4.965',
    ),
    'beta0_QCD': ConstantSpec(
        symbol='beta0_QCD',
        name='QCD one-loop beta coefficient (nf=3)',
        value=9.0,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='definition',
        uncertainty=0.0,
        notes='11 - 2*nf/3 with nf=3 light flavors; the leading QCD beta-function coefficient.',
        related_formulas=['qcd_transmutation'],
    ),
    'c': ConstantSpec(
        symbol='c',
        name='speed of light',
        value=299792458.0,
        unit='m/s',
        mass_dim=0,
        tier='established',
        source='definition',
        notes='= 1 in natural units; defines the length<->time conversion',
    ),
    'e_C': ConstantSpec(
        symbol='e_C',
        name='elementary charge (SI)',
        value=1.602176634e-19,
        unit='C',
        mass_dim=0,
        tier='established',
        source='definition',
        notes='SI charge unit (exact since 2019); distinct from e_em = sqrt(4 pi alpha)',
    ),
    'e_em': ConstantSpec(
        symbol='e_em',
        name='EM coupling (natural units)',
        value=0.3028221207683449,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='e = sqrt(4 pi alpha); charge is dimensionless in natural units',
    ),
    'epsilon_0': ConstantSpec(
        symbol='epsilon_0',
        name='vacuum electric permittivity',
        value=8.8541878188e-12,
        unit='F/m',
        mass_dim=0,
        tier='established',
        source='convention',
        uncertainty=1.4e-21,
        aliases=['eps0'],
    ),
    'hbar': ConstantSpec(
        symbol='hbar',
        name='reduced Planck constant',
        value=1.0545718176461565e-34,
        unit='J*s',
        mass_dim=0,
        tier='established',
        source='definition',
        notes='= 1 in natural units; defines action (h is SI-exact since 2019)',
    ),
    'k_B': ConstantSpec(
        symbol='k_B',
        name='Boltzmann constant',
        value=1.380649e-23,
        unit='J/K',
        mass_dim=0,
        tier='established',
        source='definition',
        notes='= 1 in natural units; defines the energy<->temperature conversion',
    ),
    'k_N': ConstantSpec(
        symbol='k_N',
        name='nucleon mass in units of Lambda_QCD',
        value=3.842,
        unit='dimensionless',
        mass_dim=0,
        tier='derived',
        source='derived',
        uncertainty=0.5,
        notes='m_n / Lambda_QCD. An O(1) non-perturbative number computed by lattice QCD from alpha_s alone -- NOT a free parameter. ~99% of the nucleon mass is QCD binding energy (current-quark mass is ~1%), so the nucleon scale is dimensional transmutation, not a Higgs Yukawa.',
        related_formulas=['nucleon_qcd_scale'],
    ),
    'kappa_cap': ConstantSpec(
        symbol='kappa_cap',
        name='holographic capacity density',
        value=9.5702e+68,
        unit='m^-2',
        mass_dim=2,
        tier='established',
        source='derived',
        uncertainty=2.2e+64,
        aliases=['kappa'],
        notes='kappa = c^3/(4 hbar G_N) = 1/(4 l_P^2), in nats/m^2 (nats dimensionless; x ln2 for bits). ESTABLISHED as the Bekenstein-Hawking entropy-per-area coefficient. The READING as an information capacity density of causal horizons (Freedman-Headrick bit-thread norm bound, extrapolated beyond holographic regimes) is the geometry-as-bandwidth CONJECTURE: inverted, G = c^3/(4 hbar kappa) makes G a reciprocal bandwidth, G->0 the infinite-capacity limit. Uncertainty inherited from G_N (rel 2.2e-5).',
    ),
    'l_P': ConstantSpec(
        symbol='l_P',
        name='Planck length',
        value=1.616255e-35,
        unit='m',
        mass_dim=-1,
        tier='established',
        source='derived',
        uncertainty=1.8e-40,
        notes='sqrt(hbar G_N / c^3)',
    ),
    'lambda_C': ConstantSpec(
        symbol='lambda_C',
        name='electron Compton wavelength',
        value=2.42631023538e-12,
        unit='m',
        mass_dim=-1,
        tier='established',
        source='CODATA',
        uncertainty=7.6e-22,
    ),
    'm_H': ConstantSpec(
        symbol='m_H',
        name='Higgs boson mass',
        value=125.25,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.17,
    ),
    'm_b': ConstantSpec(
        symbol='m_b',
        name='bottom-quark mass',
        value=4.18,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.03,
        notes='MS-bar m_b(m_b)',
    ),
    'm_c': ConstantSpec(
        symbol='m_c',
        name='charm-quark mass',
        value=1.27,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.02,
        notes='MS-bar m_c(m_c)',
    ),
    'm_d': ConstantSpec(
        symbol='m_d',
        name='down-quark mass',
        value=0.00467,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.0005,
        notes='MS-bar at 2 GeV',
    ),
    'm_e': ConstantSpec(
        symbol='m_e',
        name='electron mass',
        value=0.0005109989506900001,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='CODATA',
    ),
    'm_mu': ConstantSpec(
        symbol='m_mu',
        name='muon mass',
        value=0.1056583755,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
    ),
    'm_n': ConstantSpec(
        symbol='m_n',
        name='neutron mass',
        value=0.93956542194,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='CODATA',
        uncertainty=4.8e-10,
    ),
    'm_p': ConstantSpec(
        symbol='m_p',
        name='proton mass',
        value=0.9382720894300001,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='CODATA',
        uncertainty=2.9e-10,
    ),
    'm_s': ConstantSpec(
        symbol='m_s',
        name='strange-quark mass',
        value=0.0934,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.008,
        notes='MS-bar at 2 GeV',
    ),
    'm_t': ConstantSpec(
        symbol='m_t',
        name='top-quark mass',
        value=172.57,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.29,
        notes='pole mass',
    ),
    'm_tau': ConstantSpec(
        symbol='m_tau',
        name='tau mass',
        value=1.77686,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.00012,
    ),
    'm_u': ConstantSpec(
        symbol='m_u',
        name='up-quark mass',
        value=0.00216,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='PDG',
        uncertainty=0.0005,
        notes='MS-bar at 2 GeV',
    ),
    'mmu_me': ConstantSpec(
        symbol='mmu_me',
        name='muon-to-electron mass ratio',
        value=206.7682827,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=4.6e-06,
    ),
    'mp_me': ConstantSpec(
        symbol='mp_me',
        name='proton-to-electron mass ratio',
        value=1836.152673426,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='derived',
        uncertainty=3.2e-08,
        notes='the famous ~1836; a consequence of m_p and m_e, not an independent input',
    ),
    'mu_0': ConstantSpec(
        symbol='mu_0',
        name='vacuum magnetic permeability',
        value=1.25663706127e-06,
        unit='N/A^2',
        mass_dim=0,
        tier='established',
        source='convention',
        uncertainty=2e-16,
        aliases=['mu0'],
    ),
    'mu_B': ConstantSpec(
        symbol='mu_B',
        name='Bohr magneton',
        value=9.2740100657e-24,
        unit='J/T',
        mass_dim=-1,
        tier='established',
        source='CODATA',
        uncertainty=2.9e-33,
    ),
    'r_e': ConstantSpec(
        symbol='r_e',
        name='classical electron radius',
        value=2.8179403205e-15,
        unit='m',
        mass_dim=-1,
        tier='established',
        source='CODATA',
        uncertainty=1.3e-24,
    ),
    'rho_crit': ConstantSpec(
        symbol='rho_crit',
        name='critical density of the universe',
        value=8.53e-27,
        unit='kg/m^3',
        mass_dim=4,
        tier='established',
        source='derived',
        notes='rho_crit = 3 H_0^2 / (8 pi G_N)',
    ),
    's12sq': ConstantSpec(
        symbol='s12sq',
        name='neutrino sin^2(theta12)',
        value=0.303,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='NuFIT',
        uncertainty=0.012,
        notes='solar angle',
    ),
    's13sq': ConstantSpec(
        symbol='s13sq',
        name='neutrino sin^2(theta13)',
        value=0.02225,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='NuFIT',
        uncertainty=0.00059,
        notes='reactor angle',
    ),
    's23sq': ConstantSpec(
        symbol='s23sq',
        name='neutrino sin^2(theta23)',
        value=0.451,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='NuFIT',
        uncertainty=0.019,
        notes='atmospheric angle',
    ),
    'sigma_SB': ConstantSpec(
        symbol='sigma_SB',
        name='Stefan-Boltzmann constant',
        value=5.6703744191844314e-08,
        unit='W/(m^2*K^4)',
        mass_dim=0,
        tier='established',
        source='derived',
        notes='sigma = pi^2 k_B^4 / (60 hbar^3 c^2)',
    ),
    'sigma_T': ConstantSpec(
        symbol='sigma_T',
        name='Thomson cross section',
        value=6.6524587051e-29,
        unit='m^2',
        mass_dim=-2,
        tier='established',
        source='CODATA',
        uncertainty=6.2e-38,
    ),
    'sin2_thetaW': ConstantSpec(
        symbol='sin2_thetaW',
        name='weak mixing angle',
        value=0.23122,
        unit='dimensionless',
        mass_dim=0,
        tier='established',
        source='PDG',
        uncertainty=4e-05,
        aliases=['weinberg_angle'],
        notes='sin^2(theta_W), on-shell-ish',
    ),
    't_P': ConstantSpec(
        symbol='t_P',
        name='Planck time',
        value=5.391247e-44,
        unit='s',
        mass_dim=-1,
        tier='established',
        source='derived',
        uncertainty=6e-49,
        notes='sqrt(hbar G_N / c^5)',
    ),
    'v': ConstantSpec(
        symbol='v',
        name='Higgs vacuum expectation value',
        value=246.21965,
        unit='GeV',
        mass_dim=1,
        tier='established',
        source='derived',
        aliases=['higgs_vev'],
        notes='electroweak scale; v = (sqrt(2) G_F)^(-1/2)',
    ),
}
